### ISSUE TITLE
Github Projects作成

### ISSUE THREAD

**Issue by Shogoy0178** [Shogoy0178/myapp#4]

**Comment by Shogoy0178** [comment]
### Webアプリの概要
お気に入りの映画の楽曲を共有するサービスです。映画を見る楽しみの１つとして、音楽があります。オープニングやエンディング、クライマックスや何気ないシーンでも音楽が流れています。多くの人が、これまで見てきた映画に好きな音楽や思い入れのある音楽があるはずです。そのような音楽を知ってもらい、共感できるようなサービスです。自分のお気に入り楽曲を共有するだけでなく、新しい映画や音楽を発見することができます。映画と音楽を紐づけた投稿には、映画の予告編を閲覧できるようにし、見る映画に悩んでいる人も音楽を切り口に、見たい映画を探すことができます。

### 1週間あたりの開発に充てられる時間
15時間

### ProjectsのURL
https://github.com/users/Shogoy0178/projects/1

### MVPリリースまで
- [x] rails立ち上げ
- [x] デプロイ
- [x] API接続
- [x] ユーザ登録機能
- [x] ログイン機能
- [x] 投稿一覧機能
- [x] 投稿作成機能
- [x] 投稿編集機能
- [x] 投稿詳細機能
- [x] コメント機能
- [x] いいね機能
- [x] ページネーション機能
- [x] 検索機能

### MVP後
- [x] パスワードリセット機能
- [x] 問い合わせ機能
- [x] 退会フォーム
- [x] レスポンシブデザイン
- [x] 利用規約
- [x] プライバシーポリシー

### MVPレビュー依頼予定日
2025年1月5日

**Comment by tmtkzk0823** [comment]
ご提出ありがとうございます。
以下、コメントなります。

---

- 「ログイン機能」のissueはありますが、「ログアウト機能」のissueが見受けられませんでした。こちら、ご確認をお願いします。

- 投稿、コメントの「削除機能」のissueはなくても良さそうでしょうか？

**Comment by Shogoy0178** [comment]
フィードバックありがとうございます。
issue更新いたしました。ご確認ください。
https://github.com/users/Shogoy0178/projects/1

- ログイン機能のissueにログアウトを含むようにしました。
- 投稿削除は投稿編集のissueに含む予定なので、追加なしです。
- コメント削除について、新しくコメント編集というissueを追加いたしました。

**Comment by beppumasaki** [comment]
概ね良いかと思います。LGTMです。
